### ISSUE TITLE
API refactor request-use object methods to call query/mutation

### ISSUE THREAD

**Issue by capaj** [acro5piano/typed-graphqlify#1]
apollo client and many other clients have this kind of API:

```
graphqlify.mutation({...})
graphqlify.query({...})
```

and it feels nicer to write/read than
```js
graphqlify('mutation', {...})
graphqlify('query', {
```
also saves one character.
So I know it's a little presumptuous to ask you to change it, but IMHO it would help people who are mostly used to apollo/urql up to speed faster.

If you'd agree I could even open a PR to address this.

**Comment by acro5piano** [comment]
Thank you for your feedback, @capaj !

So nice suggestion, I completely agree with you. Could you create a PR?

**Comment by capaj** [comment]
Sure. Give me a an hour or so.
