### ISSUE TITLE
Any way to provide on_conflict in mutation

### ISSUE THREAD

**Issue by relvao** [acro5piano/typed-graphqlify#167]
I can't seem to be able to pass a on_conflict object to a mutattion. the update_columns field is always being converted from an array into an object. 

I'm using hasura as the gql server https://hasura.io/docs/1.0/graphql/core/mutations/upsert.html#update-selected-columns-on-conflict

Is this currently unsuported?

**Comment by relvao** [comment]
Update. Passing the array as a string seems to work for me:

`
              on_conflict: {
                constraint: 'listings_pkey',
                update_columns: '[name, description]'
              }
`

**Comment by acro5piano** [comment]
Thanks for the information!
