### ISSUE TITLE
Error: Object cannot have no fields at renderObject

### ISSUE THREAD

**Issue by talivodworks** [acro5piano/typed-graphqlify#198]
I am trying to implement a hasura mutation which looks like this:
```gql
mutation insertInviteMutation($objects: [invites_insert_input!]!, $on_conflict: invites_on_conflict) {
	insert_invites(object: $objects, on_conflict: $on_conflict) {
		id
		created_at
	}
}
```

My typescript code looks like this.

```ts
import { mutation, params, types} from 'typed-graphqlify';

const insetInviteMutation = mutation('myMutation ($objects: [invites_insert_input!]!, $on_conflict: invites_on_conflict)', {
	insert_invites: params(
		{
			objects: '$objects',
			on_conflict: '$on_conflict'
		},
		{
			id: types.string,
			created_at: types.string,
		}
	)
}).toString();

// I have even tried doing it through nested params

const nestedInsertInviteMutation = mutation('myMutation', params(
		{
			"$objects": "[invites_insert_input!]!",
			"$on_conflict": "invites_on_conflict"
		},
		{
			insert_invites: params(
				{
				objects: '$objects',
				on_conflict: '$on_conflict'
				},
				{
					id: types.string,
					created_at: types.string,
				}
			)
		}
	)
).toString();
```

But I got the error that **Error: Object cannot have no fields at renderObject**.
I have debugged it and its at [this line ](https://github.com/acro5piano/typed-graphqlify/blob/d98329e289505e6346a31b92c582549d988598dd/src/render.ts#L228). I can also see the test cases for [these scenario](https://github.com/acro5piano/typed-graphqlify/blob/d98329e289505e6346a31b92c582549d988598dd/src/__tests__/index.test.ts#L755-L803). But for some reasons I am getting the error. You have added these test case after [this](https://github.com/acro5piano/typed-graphqlify/issues/82#issuecomment-618165695) I guess 

I am running the latest version `3.0.2`.
Please guide me what I am doing wrong here. Thank You.

**Comment by acro5piano** [comment]
Hey @talivodworks , Thank you for using typed-graphqlify.

It's strange. I copy & paste your code in my vim and run it locally, and the result is **what we expected**. using 3.0.2

![image](https://user-images.githubusercontent.com/10719495/102237889-7b0b7900-3f38-11eb-9e23-b28c3579dd3d.png)

**Comment by acro5piano** [comment]
If you are still in a trouble, can you try the following?

- Copy the following code at the bottom of `src/__tests__/index.ts`
- Run `yarn test`

```
test.only('render directive', () => {
  const nestedInsertInviteMutation = mutation(
    'myMutation',
    params(
      {
        $objects: '[invites_insert_input!]!',
        $on_conflict: 'invites_on_conflict',
      },
      {
        insert_invites: params(
          {
            objects: '$objects',
            on_conflict: '$on_conflict',
          },
          {
            id: types.string,
            created_at: types.string,
          },
        ),
      },
    ),
  ).toString()

  console.log(nestedInsertInviteMutation)

  expect(nestedInsertInviteMutation).toBeTruthy()
})
```

**Comment by talivodworks** [comment]
@acro5piano  I have tried the provided sample test. It is working fine. I will take a deep look at my Implementation again. This is strange. I will try look more into my implementation. Thank you.

**Comment by acro5piano** [comment]
@talivodworks Yeah, please check it again. 

I'm closing this issue, but feel free to re-open if you want. Thanks!
