### ISSUE TITLE
how to query __params field?

### ISSUE THREAD

**Issue by capaj** [acro5piano/typed-graphqlify#2]
using `__params` to pass graphql parameters to a field resolver is nice, but what if I have an API which has `__params` field? How can I tell the typed-graphqlify that the `__params` is a field-not a params object?

I know it's not very likely, but it could happen.

**Comment by acro5piano** [comment]
Thank you for pointing out. Yes, that could happen.

In my opinion, we can simply write our query params as just string:

Before:

```ts
    const queryObject = {
      updateUser: {
        __params: { $name: 'String!' },
        updateUser: {
          __params: { name: '$name' },
          id: types.number,
        },
      },
    }
```

after:

```ts
    const queryObject = {
      'updateUser($name: String!)': {
        'updateUser(name: $name)': {
          id: types.number,
        },
      },
    }
```

I think the latter is more readable.
Do you have any idea?

**Comment by capaj** [comment]
oh this is a nice solution! I was thinking more of utilizing a special function:

```ts
   import {parametrized} from 'typed-graphqlify'
    const queryObject = {
      updateUser: parametrized({ $name: 'String!' }, {
        updateUser: parametrized({ name: '$name' }, {
          id: types.number,
        }),
      }),
    }
```

but your proposal is much nicer IMHO. Wouldn't it be a problem for typescript? Because the typescript type would have property `updateUser(name: $name)` instead of `updateUser`. How can we solve that?

One other thing I would love to avoid is double declaration problem that plagues graphQL queries. Other people have tried to fix it previously-for example https://github.com/sw-yx/babel-blade
I think it should be easily solvable in typed-graphqlify.

**Comment by acro5piano** [comment]
> Wouldn't it be a problem for typescript? Because the typescript type would have property updateUser(name: $name) instead of updateUser. How can we solve that?

Oh I missed the problem! Thanks.
Your `parametrized` looks great, I will try to implement that. Of course if you have time to implement it feel free to send a PR!

> One other thing I would love to avoid is double declaration problem that plagues graphQL queries. Other people have tried to fix it previously-for example https://github.com/sw-yx/babel-blade
> I think it should be easily solvable in typed-graphqlify.

It is really great if typed-graphqlify solves the double declaration problem, but how do you implement the feature?
I cannot imagine how to stop Overfetching before running the query...

**Comment by capaj** [comment]
@acro5piano if I have time I'll try to experiment with the #9 rather than this. The current implementation is good enough to be used as is. Maybe later if you don't beat me to it.

**Comment by capaj** [comment]
I noticed you even use it with arrays which gets a little hairy-because then `__params` needs to be defined on a first item of an array. I have it implemented currently on my local development branch as:

```ts
export function params<T extends object>(params: object, fields: T): T {
  paramsWeakMap.set(fields, params)
  return fields
}
```

and that works nicely! Will open a big PR soon.

**Comment by luvies** [comment]
Wouldn't ES6 symbols be perfect for something like this? e.g.
```ts
// in something like `symbols.ts`
export const gqlSymbols = {
  params: Symbol('gql-params'),
};
```
so then the example given above would be:
```ts
const queryObject = {
  updateUser: {
    [gqlSymbols.params]: { $name: 'String!' },
    updateUser: {
      [gqlSymbols.params]: { name: '$name' },
      id: types.number,
    },
  },
}
```
It preserves the in-line style and simpliciy, but ensuring that you will never get any clashes. It would also work for things like #28, where you've build up strings as placeholders.

**Comment by capaj** [comment]
@luvies interesting idea, but I think a `params` which is modeled according to [the recently merged](https://github.com/acro5piano/typed-graphqlify/pull/21) `alias` would be the best solution here.

```ts
import {params} from 'typed-graphqlify'
const queryObject = {
  [params('maleUser', {id: 1})]: {
    id: types.number,
    name: types.string,
    bankAccount: {
      id: types.number,
      branch: types.string,
    },
  }
}
```

internally I believe Weakmaps are the cleanest solution for storing metadata about objects. Symbols are great too, but it's IMHO cleaner to store it outside of the object.

**Comment by capaj** [comment]
also composing `params` and `alias` might be confusing, so it might be best to allow alias inside the params first argument
```ts
import {params} from 'typed-graphqlify'
const queryObject = {
  [params({user: 'maleUser'}, {id: 1})]: {
    id: types.number,
    name: types.string,
    bankAccount: {
      id: types.number,
      branch: types.string,
    },
  }
}
```

**Comment by luvies** [comment]
That style of function looks like it would be very clean, I agree. Plus it would properly support scalar properties, which is better than the current method. However, wouldn't the weakmaps method require a global state when building up the query objects? Considering the example implementation you gave before, if you used the same object (a little weird, but very possible) to define the params of a given query (maybe there are multiple queries that you want to use the same param for), then it wouldn't properly map all of them, would it? The last one would win and the other references would get lost.

If you needed a global state, then using a symbol as the actual key, and map from symbol to config data would work better, and be more robust overall. Even if this isn't the best implementation, you will need to consider that 99% of all query objects made using this library would last the duration of the app, created on start and only destroyed when the app shuts down, however they may only be parsed occationally and randomly.

**Comment by acro5piano** [comment]
@luvies Thank you for your comment!

> It preserves the in-line style and simplicity

Symbol is interesting idea. However, actually I don't like the current inline style, because it is far from native GraphQL style. Some users may confuse where to write params.

@capaj 's `params` dynamic property style looks good. I think we implement it without using global state and Weakmap right?

The simplest but not elegant solution is to use string literal:

```ts
import { graphqlify, params } from 'typed-graphqlify'

graphqlify.query('getFilteredUser($gender: String!)', {
  [params('maleUsers', 'users(gender: $gender)')]: {
    id: types.number,
    name: types.string,
  }
})
```

renders

```graphql
query getFilteredUser($gender: String!) {
   maleUsers: users(gender: $gender ) {
    id
    name
  }
}
```

**Comment by luvies** [comment]
Would it be possible to support typing the params? E.g. you could define the params object like
```ts
interface Params {
  page: number;
  size: number;
}
```
and then use it in the converter function like
```ts
graphqlify.query<Params>(query);
```
This would then check that all of the params were specified in the root query object, and you can also use it to make sure that you pass the right variables when actually making the query later.

To support it in the query object, it would probably have to require you to write the param without the `$`, however it would add to the type-checked support this package gives.

**Comment by acro5piano** [comment]
@luvies 
Great feature, I like it. 
I would like to keep this library as simple as possible, and type-checking does not break the simplicity.

@capaj @luvies @YardWill 
I think we will release v2.0.1 after resolving this issue, cause this issue may include the biggest breaking change.
I will try to think the api, so if you have any ideas feel free to write down. Thanks!

**Comment by acro5piano** [comment]
Something like this

```ts
graphqlify.mutation('updateUserMutation', { $name: types.string }, {
  updateUser: parameterized({ name: '$name' }, {
      id: types.number,
  }),
})
```

Renders

```gql
mutation updateUserMutation($name: String!) {
  updateUser(name: $name) {
    id
  }
}
```

More simple:

```ts
graphqlify.mutation('updateUserMutation', { $name: types.string }, {
  updateUser: $({ name: '$name' }, {
      id: types.number,
  }),
})
```

**Comment by acro5piano** [comment]
We should scalar with parameters. See #38
