### ISSUE TITLE
Quoting string values on mutations

### ISSUE THREAD

**Issue by evry-johan** [acro5piano/typed-graphqlify#208]
Using your example mutation:

```
import { mutation, params } from 'typed-graphqlify'

mutation('updateUserMutation', {
  updateUser: params(
    {
      input: {
        name: 'Ben',
        slug: '/ben',
      },
    },
    {
      id: types.number,
      name: types.string,
    },
  ),
})
```

Yields the following query: `mutation updateUserMutation{updateUser(input:{name:Ben,slug:/ben}){id name}}`. Why doesn't the library wrap string values in double quotes? That's what my backend framework expects, so I suppose it's a standard?

**Comment by acro5piano** [comment]
@evry-johan 
Hi, thanks for pointing out. You should use `rawString` helper to add `"`.

As you said, the example is wrong. I'll fix it.

**Comment by acro5piano** [comment]
Ideally typed-graphqlify wraps string automatically, but it is almost impossible to distinguish Enum and string. consider this case:

```
query {
  updateUser: params(
    {
      input: {
        name: rawString('Ben'),
        status: 'ACTIVE',
      },
    },
    {
      id: types.number,
    },
  ),
}
```

If you have any idea of it, please let me know!

And the docs is fixed by this. Thanks!

https://github.com/acro5piano/typed-graphqlify/commit/68b98beabf033ab3befec889db208242998ebfc1

**Comment by evry-johan** [comment]
@acro5piano Gotcha, thanks for the clarification. At the moment I'm doing this:

```
const createMutation = (changedEntity: Partial<Entity>) => {
  const asset = _.reduce(changedAsset, (acc, curr, key) => {
    if(_.isString(curr)) {
      acc[key] = rawString(curr)
    }
    return acc
  }, {} as { [key: string]: any })
```

Also, thanks for a nice lib, keep up the good work! 👍

**Comment by acro5piano** [comment]
@evry-johan thanks! If you have good solutions for this, I'm welcome to any PRs.

**Comment by sirganya** [comment]
This works: 

```javascript
const getStack = query("GetStack", {
  getStack: params(
    { ownerName: rawString("tkn"), stackFileName: rawString("test") },
    { code: types.string },
  ),
});
```
