### ISSUE TITLE
Is it possible to pass arguments to a field?

### ISSUE THREAD

**Issue by zabavnikov** [acro5piano/typed-graphqlify#210]
Example:

![image](https://user-images.githubusercontent.com/8766240/105315291-a9443e80-5bf1-11eb-90f5-078f89378e0e.png)

**Comment by acro5piano** [comment]
Let me check it

**Comment by acro5piano** [comment]
@zabavnikov I confirmed that your case works. I've added the query to unit test. You can refer it.

https://github.com/acro5piano/typed-graphqlify/blob/e9b48d6733027e35a8047af81f56e6ca2b524e39/src/__tests__/index.test.ts#L1020-L1036

I've also update the document.

https://github.com/acro5piano/typed-graphqlify/blob/master/README.md#field-with-arguments

If you have any problem with it, feel free to reopen this issue. Thanks!

**Comment by zabavnikov** [comment]
@acro5piano, thanks a lot! 😊
