### ISSUE TITLE
[Question]: Error handling

### ISSUE THREAD

**Issue by lo1tuma** [acro5piano/typed-graphqlify#255]
Hi,

I was desperately searching for a typescript graphql client library that doesn’t rely on code generation, it this one could be a perfect match. However I do have some questions that are not covered by the README.

* How does error handling work? There are different kind of errors (e.g. networking errors vs graphql errors). So how can I provide the schema/typings for graphql errors?
* How to handle partial data, e.g. when there are some graphql errors for only a few fields but not all?
* What happens if the data that is delivered by the server doesn’t match the expected schema? Is it possible to opt-in runtime validation, e.g. via [`zod`](https://github.com/colinhacks/zod)?

**Comment by YardWill** [comment]
This lib privide a typical graphql generator only.

**Comment by acro5piano** [comment]
Year, this library actually does not request to server. Please use your favorite library (e.g. apollo client).

> What happens if the data that is delivered by the server doesn’t match the expected schema? Is it possible to opt-in runtime validation, e.g. via zod?

Though this is not current this lib's project, but static type checking & validation on compile-time is an interesting idea.

**Comment by lo1tuma** [comment]
> Yeah, this library actually does not request to server. Please use your favorite library (e.g. apollo client).
How does it work then? Does it require an explicit type assertion? IMHO that reduces the quality of type safety. And apart from that I guess it also covers any other cases like partial reponse/error scenarios, right? So I can’t have the correct type definition for a partial data response, right?

**Comment by lo1tuma** [comment]
I think I got that now. Although I still understand how the type could match for `.data` when there is a  partial error/data response. Is everything made optional by default?
Anyway, thanks for all the answers I have a much better understanding of what this library is able to do.

**Comment by acro5piano** [comment]
Yeah, this library just converts object into string. No requests/response/partial-errors. 

Practically you should your favorite GraphQL client library with typed-graphqlify like Apollo, URQL, or even primitive `fetch`.
