### ISSUE TITLE
Proper way of creating scalar with parameters

### ISSUE THREAD

**Issue by humodz** [acro5piano/typed-graphqlify#38]
First of all, thanks for creating this awesome library. My question is, how should I create a field that takes parameters, but returns a scalar instead of a nested object?

Example:
```gql
type Query {
  getContract: Contract
}

type Contract {
   title: String!
   isValid(timestamp: String!): Boolean!
}
```
Desired query:
```gql
query {
  getContract {
    title: String!
    isValid(timestamp: "2019-01-30")
  }
}
```
I can't use __params, because graphqlify will generate an empty { } block after the name and parameters.

My workaround:
```ts
const contractObj = {
  title: types.string,
  isValid: types.boolean, // for type inference and auto-compĺetion to work properly
}

delete contractObj.isValid;
contractObj['isValid(timestamp: "2019-01-30")'] = types.boolean;

const queryObj = { getContract: contractObj };
const queryString = graphqlify.query('MyQuery', queryObj);
```
I could have added `['isValid(timestamp: "2019-01-30")']: types.boolean` to the object literal, but then auto-completion, type inference, etc, wouldn't work as desired.

Is something like this possible?
```ts
const contractObj = {
  title: types.string,
  isValid: withParameters(types.boolean, { timestamp: '"2018-01-01"' }),
};
```

**Comment by acro5piano** [comment]
Hi @humodz , thank you for your interest and suggestion!

Yes, it does not support scalar with parameters yet.
Currently working on #2 so the feature should be support there.

Anyway, your `withParameters` sounds good!
