### ISSUE TITLE
Verifying a queryObject and have typeof getAbout.data the expected type?

### ISSUE THREAD

**Issue by nestarz** [acro5piano/typed-graphqlify#383]
Hello ! Thank you for your work!!

I would like to do

```tsx
/* ../../types.d.ts */
type About = {
  id: number;
  title: string;
  count: number;
  not_queried: string;
};

import type * as GqlTypes from "../../types.d.ts";

const getAbout = query<GqlTypes.Query>("GetAbout", {
  about_by_pk: params(
    { id: 1 },
    { title: types.string, invalid_field: types.string, count: types.boolean },
  ),
});
```

Where `invalid_field` and `count` would be incorrect. And have typeof getAbout.data have the partial About type hence without not_queried.

Right now, by doing so, getAbout.data will have GqlTypes.Query type.

Do you have any idea ?

**Comment by acro5piano** [comment]
I'm not sure this works, but how about this?

```tsx
import { CompiledResult, query } from 'typed-graphqlify'

const getAbout: CompiledResult<GqlTypes.Query, any> = query("GetAbout", {
  about_by_pk: params(
    { id: 1 },
    { title: types.string, invalid_field: types.string, count: types.boolean },
  ),
});
```

**Comment by acro5piano** [comment]
By the way, I recommend you to use the generated type directly if you use a codegen tool. For apollo client example:

```tsx
const getAbout = apolloClient.query<GqlTypes.Query>(' ...
```

If you use React, you can use the hook from the generated code:

```tsx
import { useGetAboutQuery } from 'generated.graphql.ts'

const { data } = useGetAboutQuery()
```

This is more robust and simpler than typed-graphqlify, so I don't recommend this library anymore (Sadly).

**Comment by nestarz** [comment]
Thank you @acro5piano, the reason is that I would like to have a solution that doesn't require codegen on the client side, for minimal code footprint, only on the server side code generation is permitted, that's where GqlTypes is generated based on the graphql schema. 

Dont you think that based on the GraphQL schema its enough to have robust and simple type inference for queries ? What bring a codegen tool if we can do proper type inference based on the query and the schema ?

Here is my current solution:

```ts
const getAbout = query<GqlTypes.Query>("GetAbout", {
  about_by_pk: params(
    { id: 1 },
    {
      title: types.optional.string,
      description: types.optional.string,
    }
  ),
  collections: [
    {
      id: types.number,
      title: types.string,
    },
  ],
});

const result = await graphql<typeof getAbout.data>({
  query: getAbout.toString(),
});
```

But this lacks simplicity and will permit to use any field of GqlTypes.Query even if not retrieved, I'm searching for a better type inference. I think your implementation has great potential to have great types without queries codegen.

**Comment by acro5piano** [comment]
> Dont you think that based on the GraphQL schema its enough to have robust and simple type inference for queries ? What bring a codegen tool if we can do proper type inference based on the query and the schema ?

It ensures the types are generated from not by hand but the actual schema, meaning compile-time type safety instead of runtime one. I understand in some situations we cannot use the codegen tools, so this is tradeoff.

If you want to stick to the typing by hand, please forget about the type safety among the generated code. This library is not created for these kind of use-case. Sorry!
