### ISSUE TITLE
Support inline fragment unions

### ISSUE THREAD

**Issue by luvies** [acro5piano/typed-graphqlify#40]
I've been writing both a GraphQL server and consumer, and I've written a pattern of using discriminatory unions multiple times. Unfortunately, the way fragments work currently, it just makes each field optional, making it a bit weird to handle these kinds of unions properly. Ideally, you would want something that could mimic the following:

```ts
interface ObjA {
  name: 'a';
  prop: string;
}

interface ObjB {
  name: 'b';
  field: number;
}

type Union = ObjA | ObjB;
```

So far, this is the implementation I'm using, however, it's a *little* odd, so would need discussion before actually being implemented here:

```ts
export function onUnion<T extends Array<{}>>(typeNames: string[], fields: T): T extends Array<infer TElement> ? TElement : never {
  if (typeNames.length !== fields. length) {
    throw new Error('Type name and field arrays must be the same length');
  }

  let obj: any = {};

  for (let i = 0; i < fields.length; i++) {
    obj = {
      ...obj,
      ...on(typeNames[i], fields[i]),
    };
  }

  return obj;
}
```

Unfortunately, I have to make it accept 2 lists, one with type names and one with field objects, since otherwise TS didn't infer the types properly.

Using this function looks like so:

```ts
const query = {
  ...onUnion(
    [
      'ObjA',
      'ObjB',
    ],
    [
      {
        name: types.constant('a'),
        prop: types.string,
      },
      {
        name: types.constant('b'),
        field: types.number,
      },
    ],
  ),
};
```

**Comment by acro5piano** [comment]
Thank you for posting an issue!

I'm not familiar with fragment unions, so could you write some example code? Minimal (failing) unittest code is very helpful. 
Thanks!

**Comment by luvies** [comment]
It's not a true feature of GraphQL, per-se, but it's a pattern a lot of unions follow I believe. To use the example above, you could do the following in GQL

```gql
# This interface is not actually needed, but I tend to use it since it makes sense & is more readable
interface IBaseObj {
  name: String!
}

type ObjA implements IBaseObj {
  name: String!
  prop: String!
}

type ObjB implements IBaseObj {
  name: String!
  field: Number!
}

union Objs = ObjA | ObjB;
```

If you then ensure that `name` is always a value for a given type (e.g. `a` for `ObjA`, and `b` for `ObjB`), then clients can effectively discriminate between them using the name property, which always exists. For example:

```ts
const obj = query(...); // Union of ObjA & ObjB

if (obj.name === 'a') {
  console.log(obj.prop); // since we know a name of 'a' always means we got `ObjA`, we can guarantee the properties
} else if (obj.name === 'b') {
  console.log(obj.field); // same here, this will always be `ObjB`
}
```

TypeScript supports this via its type-narrowing system, making it work very well, especially when both sides are TS. The main request here is that we provide a slightly higher-level function than `on` that allows us to express this kind of union, which would make consuming code a bit better to work with, since you currently have to deal with possibly undefined properties (once you know what the type of the object you got back was, you know that all the other fields of this object are defined, but that isn't expressed properly right now).

A side effect of this kind of function, is that it cleanly supports unions where the object could have the same names for some properties, but different types, e.g.

```gql
interface IValue {
  type: String!
}

type StringValue implements IValue {
  type: String!
  value: String!
}

type IntValue implements IValue {
  type: String!
  value: Int!
}

union Value = StringValue | IntValue
```

To query this, you would use the following (using the sample implementation I wrote)

```ts
const query = {
  values: {
    ...onUnion(
      [
        'StringValue',
        'IntValue',
      ],
      [
        {
          type: types.constant('string'),
          value: types.string,
        },
        {
          type: types.constant('int'),
          value: types.number,
        },
      ],
    ),
  },
};
```

and it would parse to the following

```gql
query {
  values {
    ... on StringValue {
      type
      value
    }
    ... on IntValue {
      type
      value
    }
  }
}
```

**Comment by acro5piano** [comment]
Thank you for your example code!

Just confirming the problem.
Assuming this query:

```typescript
const queryObject = {
  hero: {
    id: types.number,
    type: types.string, // <--- expected 'droid' | 'human'
    ...on('Droid', {
      memory: types.number,
    }),
    ...on('Human', {
      height: types.number,
    }),
  },
}
```

and the interface of `typeof queryObject` becomes:

```
interface (typeof queryObject) {
    hero: {
        id: number
        type: string
        memory?: number
        height?: number
    }
}
```

The problem is `height` and `memory` become optional, right?

If `type` is `droid`, `memory` must definitely not `undefined`.

**Comment by luvies** [comment]
Correct, the problem is that it simply merges all of the properties of all the inline fragments into the object, making the typing not line up to what is actually returned (e.g. `Droid` never has the property `height`, however this will always exist on the typing regardless using the current system).

As for the `when` function you've shown, I don't think that would work well. The discriminatory union is only a pattern, it isn't enforced by GraphQL, so it might artificially restrict what can be done. I could very much see the case for supporting this with objects that have *no* matching properties, and supporting the union typing would help with using them I think.

There's also the issue of inferring the typing. With this, TS is quite particular about it, and it's the reason my implementation looks the way it does. I would need to look into if there is another way of doing it, however the current implementation uses the fact that the implicit typing of `T` will become something like `(a | b)[]` when fields is set to `[a, b]`, and from that you can extract the element values individually and convert it to a union of them in the return type. I don't think we can do quite the same thing with the method you showed.

As a side note, the typing for my implementation actually was derived from `type-graphql` and how it deals with unions. If you want to look further into how it works, that might be a good place to start?

**Comment by acro5piano** [comment]
I'm sorry for my slow response, and thank you for your suggestion!

> As a side note, the typing for my implementation actually was derived from `type-graphql` and how it deals with unions. If you want to look further into how it works, that might be a good place to start?

Yes for sure. Thank you for your suggestion from deriving the good library.

You mean your `onUnion` function is the only way to implement TS' type inference?
Can we implement it like the following object? looks simpler.

```ts
const query = {
  ...onUnion({ 
      ObjA: {
        name: types.constant('a'),
        prop: types.string,
      },
      ObjB: {
        name: types.constant('b'),
        field: types.number,
      },
  }),
};
```

And recently I don't have much time to work on the following issues:

- https://github.com/acro5piano/typed-graphqlify/issues/2
- https://github.com/acro5piano/typed-graphqlify/issues/40
- https://github.com/acro5piano/typed-graphqlify/issues/41
- https://github.com/acro5piano/typed-graphqlify/issues/42
- https://github.com/acro5piano/typed-graphqlify/issues/43

I will definitely solve them, but if you can work on them before me, could you create PRs?
I am also open to invite you to co-maintainers, as I don't want to make development slow for my schedule.

Best regards

**Comment by luvies** [comment]
From my testing, that was the only way I could make it work, but I do like that way of doing it, so I'll look into it.

I'm willing to work on those issues (I only made the last 3 because I kept forgetting about them), and if you're open to me being a co-maintainer, then I'm more than willing to help (I've found this library to be very useful in my work, and I'll likely use it in personal projects once I get around to them). Also, if you're alright with me doing a little bit of a refactor, I could try and adjust the GQL builder and make it a little more robust against the issues I've found?

**Comment by acro5piano** [comment]
Yes, please make this library great together! Thank you a lot.

> Also, if you're alright with me doing a little bit of a refactor, I could try and adjust the GQL builder and make it a little more robust against the issues I've found?

Sure, I'll review changes before merge!
