### ISSUE TITLE
API refactor

### ISSUE THREAD

**Issue by acro5piano** [acro5piano/typed-graphqlify#7]
Currently we have to write the operation name like this:

```ts
graphqlify.query({
  getMotherAndFather: {
    mother: {
      id: types.number,
    },
    father: {
      id: types.number,
    },
  },
})
```

Now that #6 is merged even got better, but how about this?

```ts
graphqlify.query('getMotherAndFather', {
  mother: {
    id: types.number,
  },
  father: {
    id: types.number,
  },
})
```

in this way we can avoid using hackerly `GraphQLData<queryObject>` and less typing.

**Comment by capaj** [comment]
as long as it works for nested props too and it's optional. So the two queries you wrote should be the same. Also these two should be the same:

## using a prefix

```ts
graphqlify.query('getMotherAndFather.mother', {
    id: types.number,
  })
```

## no prefix
```ts
graphqlify.query({
  getMotherAndFather {
    mother: {
      id: types.number,
    }
  }
})
```

On our GraphQL api we often have entities which are deeply nested and it would make the query simpler if we could use the prefix.

**Comment by acro5piano** [comment]
Thank you for your suggestion.
I don't know how to implement nested props, for example

`getMotherAndFather.mother`

↓

```ts
interface getMotherAndFathermother {
  mother: ...
}
```

Deep nested GraphQL looks useful in the  particular situations, so I think it is the tradeoff of losing type info.
