### ISSUE TITLE
How to represent a union?

### ISSUE THREAD

**Issue by iyegoroff** [acro5piano/typed-graphqlify#74]
Hi, @acro5piano!

How to represent a type like `string | null`? I have tried `types.oneOf([types.string, null] as const)`, but this gives me some wrong type in typescript v3.6.3:

![Screen Shot 2019-10-08 at 19 47 11](https://user-images.githubusercontent.com/4447438/66415834-2ea7dd80-ea05-11e9-85f0-7a74c80b976e.png)

**Comment by acro5piano** [comment]
Hi @iyegoroff !

Currently `types.oneOf` takes `enum`, not array. We are changing it to take array element type which is being discussed here:
https://github.com/acro5piano/typed-graphqlify/issues/67

The PR is still WIP though:
https://github.com/acro5piano/typed-graphqlify/pull/68

I'm really grad if you implement it. Thanks!

**Comment by coffenbacher** [comment]
Looking forward to that PR @acro5piano ! In the meantime, I think this workaround is working for me:

```
function nullable<T>(obj: T): T | null {
  return obj
}

...
access: nullable(types.string)
...
```
