### ISSUE TITLE
Params of type array is not formatted correctly in Mutation.

### ISSUE THREAD

**Issue by talivodworks** [acro5piano/typed-graphqlify#82]
I am trying to create a bulk insert mutation with parameter of type array For example
`mutation {`
`    insert_users: (`
`        objects:[ {name: "test"}, {name: "test2"} ]`
`   )`
` { returning: { id }}`
`}`
my graphql server support objects to be an array. so using typed-graphiql I am generating this mutation like this 
`const bulkInsertQuery = { inserts_users: params([ {name: "test"}, {name: "test2"} ], {returning: {id: type.number}})};`
`const graphqlQuery = mutation(bulkInsertQuery)`

this output query is something like this 
`mutation{insert_users: (object: {0: {name: "test"}, 1: {name: "test2"} } ) };`

Is there a way to keep the array as it is without converting it into key values?

Any help would be appreciated. Thank you

**Comment by acro5piano** [comment]
@talivodworks 
Thanks for your report.
I'm trying to check and solve your use case.

**Comment by acro5piano** [comment]
Are you expecting the following input/output right?

input:

```ts
const mutationObject = {
  insert_users: params({
    objects: [ {name: "test"}, {name: "test2"} ]
  },  {
    returning: { id: types.number }
  })
}
```

output:

```gql
mutation {
  insert_users: (
    objects: [ {name: "test"}, {name: "test2"} ]
  )  {
    returning: { id }
  }
}
```

**Comment by talivodworks** [comment]
@acro5piano yes that is correct.

**Comment by acro5piano** [comment]
I've tried to implement array pattern, but I found it needs a lot of `rawString` to detect string object.

Instead, can you try pass `objects` as GraphQL variables like this?

https://github.com/acro5piano/typed-graphqlify/pull/84/files#diff-da4ff8448db4257666fc4d253664f72eR693-R713

**Comment by talivodworks** [comment]
@acro5piano  I am sorry but I do not understand. Can you please convert
https://github.com/acro5piano/typed-graphqlify/issues/82#issuecomment-618155473
to what you mean by using the object. That would be helpful.
Thank You.

**Comment by acro5piano** [comment]
@talivodworks 
There are two ways to send parameters by GraphQL.

The first one is embedded parameters, which is something like you suggested.

```graphql
mutation HasuraBulkInsertUsers {
  insert_users: (
    objects: [ {name: "test"}, {name: "test2"} ]
  )  {
    returning: { id }
  }
}
```

And the second one is passing argument to your query, and send the query with `variables` request body.

```
      mutation BulkInsertUsers($objects: [user_insert_input!]!) {
        insert_users(objects: $objects) {
          returning {
            id
          }
        }
      }
```

typed-graphqlify cannot covert the first one for some reasons, so you should request by sending `variables` request body.
A complete example is the following:

```
import { params, mutation, types } from 'typed-graphqlify'

const query = mutation('BulkInsertUsers', params({ $objects: '[user_insert_input!]!' }, {
        insert_users: params({ objects: '$objects' }, {
          returning: {
            id: types.number,
          },
        })
}))

fetch('https://your-server.com/graphql', { 
  method: 'POST',
  body: JSON.stringify({
    query: query,
    variables: {
      objects: [
        {name: "test"},
        {name: "test2"},
      ],
    },
  })
```

If you have still questions, feel free to reopen this issue.
Thanks

**Comment by talivodworks** [comment]
@acro5piano  Thank you so much... That worked... Really appreciate your help. :)

**Comment by acro5piano** [comment]
You are welcome!
