### ISSUE TITLE
Optional types not working?

### ISSUE THREAD

**Issue by marco2216** [acro5piano/typed-graphqlify#85]
Hi, when I define an optional type it doesn't seem to work? branch is defined as types.optional.string. Great idea for this library by the way.
<img width="413" alt="Screenshot 2020-06-03 at 21 31 04" src="https://user-images.githubusercontent.com/4561482/83681014-10b96980-a5e2-11ea-8639-524decc7b741.png">

**Comment by marco2216** [comment]
Thank you. I believe this is because strictNullCheks was not set to true on the project. But I find it odd that it would not show that the type could be undefined.

**Comment by acro5piano** [comment]
Do you mean the TSHover shows `string` instead of `string | undefined`, right?
I think it odd too. If you have any workaround on this, feel free to open a PR or post it here. Thanks.

**Comment by marco2216** [comment]
Yes, that's right. But I guess it makes sense since without strictNullChecks, any object can be null or undefined. But it would be nice if there was a way to specify that you know for sure that an object is not null or undefined.

Even NonNullable type does not do any good without strict checks:
![image](https://user-images.githubusercontent.com/4561482/83857429-44e47580-a71b-11ea-8af0-b88c228d28a5.png)
