### ISSUE TITLE
Render fragment to string

### ISSUE THREAD

**Issue by kevinsimper** [acro5piano/typed-graphqlify#87]
It looks there is no way to turn a fragment into a string.

This will make it easier to incorporate into larger projects where fragments are used as a way for splitting up the app into smaller pieces.

It will benefit that you don't have to refactor everything up the chain if you want to add it to a leaf component.

```
const userProfileFragment = fragment("UserProfile", "User", {
  name: types.string,
});
toString(userProfileFragment)
```

**Comment by acro5piano** [comment]
close via #88
